name: Check Generated CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: "Update"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install jinja
        run: python -m pip install jinja2
      - name: Generate CI
        run: .github/workflows/gen_ci.py
      - name: Add untracked files to index so they count as changes
        run: git add -A
      - name: Check output
        run: git --no-pager diff --exit-code HEAD
      - name: Generate diff
        run: git diff HEAD > ci-fixes.patch
        if: ${{ failure() }}
      - uses: actions/upload-artifact@v4
        with:
          name: ci-fixes
          path: ci-fixes.patch
        if: ${{ failure() }}
