name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        target:
          [
            { os: roborio, port: cortexa9_vfpv3 },
            { os: bionic, port: armhf },
            { os: bionic, port: arm64 },
            { os: focal, port: armhf },
            { os: focal, port: arm64 },
            { os: buster, port: armhf },
            { os: buster, port: arm64 },
            { os: bullseye, port: armhf },
            { os: bullseye, port: arm64 },
            { os: raspi-buster, port: armhf },
            { os: raspi-bullseye, port: armhf },
          ]
        host:
          [
            {
              os-cfg: linux_x86_64,
              runner: ubuntu-latest,
              container: "ghcr.io/ryanhir/toolchain-builder:latest",
            },
            {
              os-cfg: linux_arm64,
              runner: ubuntu-latest,
              container: "ghcr.io/ryanhir/toolchain-builder:latest",
            },
            {
              os-cfg: linux_armhf,
              runner: ubuntu-latest,
              container: "ghcr.io/ryanhir/toolchain-builder:latest",
            },
            {
              os-cfg: windows_i686,
              runner: ubuntu-latest,
              container: "ghcr.io/ryanhir/toolchain-builder:latest",
            },
            {
              os-cfg: windows_x86_64,
              runner: ubuntu-latest,
              container: "ghcr.io/ryanhir/toolchain-builder:latest",
            },
            {
              os-cfg: macos_x86_64,
              runner: macos-latest,
              container: "",
            }
          ]
    name: Build ${{ matrix.target.os }}-${{ matrix.target.port }} for ${{ matrix.host.os-cfg }}
    runs-on: ${{ matrix.host.runner }}
    container: ${{ matrix.host.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Prep MacOS
        if: matrix.host.runner == 'macos-latest'
        run: brew install coreutils binutils gnu-tar gzip dpkg
      - name: Import Developer ID Certificate
        uses: wpilibsuite/import-signing-certificate@v1
        with:
          certificate-data: ${{ secrets.APPLE_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        if: github.repository_owner == 'wpilibsuite' && matrix.host.runner == 'macos-latest'
      - name: Build
        run: |
          ./build.sh hosts/${{matrix.host.os-cfg}}.env targets/${{matrix.target.os}} ${{matrix.target.port}}
        env:
          APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.target.os}}-${{matrix.target.port}}-${{matrix.host.os-cfg}}
          path: build/${{matrix.target.os}}-${{matrix.target.port}}/*/${{matrix.target.port}}-${{matrix.target.os}}-*-*-Toolchain-*.*
  test-sysroot:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target:
          [
            { os: roborio, port: cortexa9_vfpv3 },
            { os: bionic, port: armhf },
            { os: bionic, port: arm64 },
            { os: focal, port: armhf },
            { os: focal, port: arm64 },
            { os: buster, port: armhf },
            { os: buster, port: arm64 },
            { os: bullseye, port: armhf },
            { os: bullseye, port: arm64 },
            { os: raspi-buster, port: armhf },
            { os: raspi-bullseye, port: armhf },
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{matrix.target.os}}-${{matrix.target.port}}-linux_x86_64
      - name: Fix directory
        run: mv x86_64-linux-gnu-Linux/* .
      - name: Print directory for logging
        run: ls -lah
      - name: Run test
        run: ./test.sh hosts/linux_x86_64.env targets/${{matrix.target.os}} ${{matrix.target.port}}
