name: Build

on:
  push:
    paths-ignore:
      - ".vscode"
      - "**.md"
  pull_request:
    paths-ignore:
      - ".vscode"
      - "**.md"

jobs:

  build-sysroot-roborio-academic-cortexa9_vfpv3:
    name: Build sysroot for roborio-academic-cortexa9_vfpv3
    runs-on: ubuntu-latest
    container: "docker.io/wpilib/opensdk-ubuntu:22.04"
    env:
      WPI_TARGET: roborio-academic
      WPI_TARGET_PORT: cortexa9_vfpv3
      WPI_USE_THREADS: 8
    steps:
      - uses: actions/checkout@v3
      - name: Install opensysroot
        run: |
          cd res/opensysroot
          python3 -m pip install .
      - name: Build sysroot
        run: |
          make backend
      - uses: actions/upload-artifact@v3
        with:
          name: roborio-academic-cortexa9_vfpv3-sysroot
          path: output/*

  build-sysroot-bullseye-arm64:
    name: Build sysroot for bullseye-arm64
    runs-on: ubuntu-latest
    container: "docker.io/wpilib/opensdk-ubuntu:22.04"
    env:
      WPI_TARGET: bullseye
      WPI_TARGET_PORT: arm64
      WPI_USE_THREADS: 8
    steps:
      - uses: actions/checkout@v3
      - name: Install opensysroot
        run: |
          cd res/opensysroot
          python3 -m pip install .
      - name: Build sysroot
        run: |
          make backend
      - uses: actions/upload-artifact@v3
        with:
          name: bullseye-arm64-sysroot
          path: output/*

  build-sysroot-raspi-bullseye-armhf:
    name: Build sysroot for raspi-bullseye-armhf
    runs-on: ubuntu-latest
    container: "docker.io/wpilib/opensdk-ubuntu:22.04"
    env:
      WPI_TARGET: raspi-bullseye
      WPI_TARGET_PORT: armhf
      WPI_USE_THREADS: 8
    steps:
      - uses: actions/checkout@v3
      - name: Install opensysroot
        run: |
          cd res/opensysroot
          python3 -m pip install .
      - name: Build sysroot
        run: |
          make backend
      - uses: actions/upload-artifact@v3
        with:
          name: raspi-bullseye-armhf-sysroot
          path: output/*



  build-platform-utils-raspi-bullseye-armhf-linux-x86_64:
    needs: [build-sysroot-raspi-bullseye-armhf]
    name: Build raspi-bullseye-armhf for linux_x86_64
    runs-on: ubuntu-latest
    container: "docker.io/wpilib/opensdk-ubuntu:22.04"
    env:
      WPI_HOST: linux_x86_64
      WPI_TARGET: raspi-bullseye
      WPI_TARGET_PORT: armhf
      WPI_USE_THREADS: 8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: raspi-bullseye-armhf-sysroot
          path: output/

      - name: Build
        run: |
          make frontend
          rm output/*.tar
      - uses: actions/upload-artifact@v3
        with:
          name: raspi-bullseye-armhf-linux_x86_64
          path: output/*

  build-platform-utils-roborio-academic-cortexa9_vfpv3-raspi-bullseye-armhf:
    needs: [build-sysroot-roborio-academic-cortexa9_vfpv3, build-platform-utils-raspi-bullseye-armhf-linux-x86_64]
    name: Build roborio-academic-cortexa9_vfpv3 for raspi-bullseye_armhf
    runs-on: ubuntu-latest
    container: "docker.io/wpilib/opensdk-ubuntu:22.04"
    env:
      WPI_HOST: raspi-bullseye_armhf
      WPI_TARGET: roborio-academic
      WPI_TARGET_PORT: cortexa9_vfpv3
      WPI_USE_THREADS: 8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: roborio-academic-cortexa9_vfpv3-sysroot
          path: output/

      - uses: actions/download-artifact@v3
        with:
          name: raspi-bullseye-armhf-linux_x86_64
          path: cross/
      - name: Install cross-compiler
        run: |
          cd cross
          find . -type f
          tar xzf *.tgz
          cd raspi-bullseye
          cp -Rp * /usr

      - name: Build
        run: |
          make frontend
          rm output/*.tar
      - uses: actions/upload-artifact@v3
        with:
          name: roborio-academic-cortexa9_vfpv3-raspi-bullseye_armhf
          path: output/*

  build-platform-utils-bullseye-arm64-linux-x86_64:
    needs: [build-sysroot-bullseye-arm64]
    name: Build bullseye-arm64 for linux_x86_64
    runs-on: ubuntu-latest
    container: "docker.io/wpilib/opensdk-ubuntu:22.04"
    env:
      WPI_HOST: linux_x86_64
      WPI_TARGET: bullseye
      WPI_TARGET_PORT: arm64
      WPI_USE_THREADS: 8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: bullseye-arm64-sysroot
          path: output/

      - name: Build
        run: |
          make frontend
          rm output/*.tar
      - uses: actions/upload-artifact@v3
        with:
          name: bullseye-arm64-linux_x86_64
          path: output/*

  build-platform-utils-roborio-academic-cortexa9_vfpv3-bullseye-arm64:
    needs: [build-sysroot-roborio-academic-cortexa9_vfpv3, build-platform-utils-bullseye-arm64-linux-x86_64]
    name: Build roborio-academic-cortexa9_vfpv3 for bullseye_arm64
    runs-on: ubuntu-latest
    container: "docker.io/wpilib/opensdk-ubuntu:22.04"
    env:
      WPI_HOST: bullseye_arm64
      WPI_TARGET: roborio-academic
      WPI_TARGET_PORT: cortexa9_vfpv3
      WPI_USE_THREADS: 8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: roborio-academic-cortexa9_vfpv3-sysroot
          path: output/

      - uses: actions/download-artifact@v3
        with:
          name: bullseye-arm64-linux_x86_64
          path: cross/
      - name: Install cross-compiler
        run: |
          cd cross
          find . -type f
          tar xzf *.tgz
          cd bullseye
          cp -Rp * /usr

      - name: Build
        run: |
          make frontend
          rm output/*.tar
      - uses: actions/upload-artifact@v3
        with:
          name: roborio-academic-cortexa9_vfpv3-bullseye_arm64
          path: output/*

  release:
    needs: [build-platform-utils-raspi-bullseye-armhf-linux-x86_64, build-platform-utils-roborio-academic-cortexa9_vfpv3-raspi-bullseye-armhf, build-platform-utils-bullseye-arm64-linux-x86_64, build-platform-utils-roborio-academic-cortexa9_vfpv3-bullseye-arm64]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Remove sysroots
        run: find -name "*.tar" -delete
      - name: Release
        uses: ncipollo/release-action@v1.11.1
        with:
          allowUpdates: true
          artifacts: "**/*"
          token: ${{ secrets.GITHUB_TOKEN }}