name: Build

on:
  push:
    paths-ignore:
      - '.vscode'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.vscode'
      - '**.md'

jobs:
  targets:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v1
      - id: set-matrix
        run: |
          # Load targets into runtime variable to reduce complexity
          JSON="$(cat .github/workflows/targets.json)"
          # Remove newlines
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "::set-output name=matrix::${JSON}"
  build:
    needs: targets
    strategy:
      matrix:
        target: ${{fromJson(needs.targets.outputs.matrix).tasks}}
        host:
          [
            {
              os-cfg: linux_x86_64,
              runner: ubuntu-latest,
              container: "ghcr.io/ryanhir/toolchain-builder:bionic",
            },
            {
              os-cfg: windows_x86_64,
              runner: ubuntu-latest,
              container: "ghcr.io/ryanhir/toolchain-builder:bionic",
            },
            {
              os-cfg: macos_x86_64,
              runner: macos-10.15,
              container: "",
            }
          ]
        include:
          - host:
              os-cfg: linux_i686
              runner: ubuntu-latest
              container: ghcr.io/ryanhir/toolchain-builder:bionic
            target:
              os: raspi-buster
              port: armhf
          - host:
              os-cfg: linux_i686
              runner: ubuntu-latest
              container: ghcr.io/ryanhir/toolchain-builder:bionic
            target:
              os: raspi-bullseye
              port: armhf
    name: Build ${{ matrix.target.os }}-${{ matrix.target.port }} for ${{ matrix.host.os-cfg }}
    runs-on: ${{ matrix.host.runner }}
    container: ${{ matrix.host.container }}
    steps:
      - uses: actions/checkout@v1
      - name: Prep MacOS
        if: matrix.host.runner == 'macos-10.15'
        run: brew install coreutils dpkg gnu-tar gzip rsync xz
      - name: Prep XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ^12.4
        if: matrix.host.runner == 'macos-10.15'
      - name: Build
        run: |
          ./build.sh hosts/${{matrix.host.os-cfg}}.env targets/${{matrix.target.os}} ${{matrix.target.port}}
      - name: Test
        if:
          matrix.host.os-cfg == 'macos_x86_64' ||
          matrix.host.os-cfg == 'linux_x86_64'
        run:
          ./test.sh hosts/${{matrix.host.os-cfg}}.env targets/${{matrix.target.os}} ${{matrix.target.port}}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.target.os}}-${{matrix.target.port}}-${{matrix.host.os-cfg}}
          path: output/*
  xcode-sign:
    needs: build
    if: github.repository_owner == 'wpilibsuite'
    strategy:
      matrix:
        target: ${{fromJson(needs.targets.outputs.matrix).tasks}}
    name: Sign macOS binaries for ${{matrix.target.os}}_${{matrix.target.port}}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Import Developer ID Certificate
        uses: wpilibsuite/import-signing-certificate@v1
        with:
          certificate-data: ${{ secrets.APPLE_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
      - uses: actions/download-artifact@v2
        with:
          name: ${{matrix.target.os}}-${{matrix.target.port}}-macos_x86_64
